MExpr msg_Generalappname;
MExpr msg_Generalargrx;
MExpr msg_Generalargtyp;
MExpr msg_Generalargmore;
MExpr msg_Generalbktmcp;
MExpr msg_Generalbktwrn;
MExpr msg_Generalcatname;
MExpr msg_Generalfile;
MExpr msg_Generalnewsym = NULL;
MExpr msg_Generalnfunfail;
MExpr msg_Generalnosite;
MExpr msg_Generalobspkgfn;
MExpr msg_Generaloffline;
MExpr msg_Generaloldversion;
MExpr msg_Generalpclt;
MExpr msg_Generalpcltn;
MExpr msg_Generalpcltni;
MExpr msg_Generalpcltnv;
MExpr msg_Generalpcltnvi;
MExpr msg_Generalplnr;
MExpr msg_Generalpp3tr;
MExpr msg_Generalpptr;
MExpr msg_Generalprefdir;
MExpr msg_Generalpwfailed;
MExpr msg_Generalshdw;
MExpr msg_Generalshdwcor;
MExpr msg_Generalsntxi;
MExpr msg_Generalspell;
MExpr msg_Generalspell1;
MExpr msg_Generalstop;
MExpr msg_Generalstring;
MExpr msg_Generalstringopt;
MExpr msg_Generalstrse;
MExpr msg_Generalsysmain;
MExpr msg_Generalwritewarn;
MExpr msg_Generalsntx;

MExpr msg_Setsetraw;
MExpr msg_Setwrsym;

MExpr msg_Inequalityineq;

MExpr msg_PowerInfy;

MExpr msg_MessageName;