{
    MString s = MString_NewC("RawTab");
    Char_RawTab = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawReturn");
    Char_RawReturn = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawEscape");
    Char_RawEscape = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawSpace");
    Char_RawSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawExclamation");
    Char_RawExclamation = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawDoubleQuote");
    Char_RawDoubleQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawNumberSign");
    Char_RawNumberSign = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawDollar");
    Char_RawDollar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawPercent");
    Char_RawPercent = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawAmpersand");
    Char_RawAmpersand = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawQuote");
    Char_RawQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawLeftParenthesis");
    Char_RawLeftParenthesis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawRightParenthesis");
    Char_RawRightParenthesis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawStar");
    Char_RawStar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawPlus");
    Char_RawPlus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawComma");
    Char_RawComma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawDash");
    Char_RawDash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawDot");
    Char_RawDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawSlash");
    Char_RawSlash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawColon");
    Char_RawColon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawSemicolon");
    Char_RawSemicolon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawLess");
    Char_RawLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawEqual");
    Char_RawEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawGreater");
    Char_RawGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawQuestion");
    Char_RawQuestion = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawAt");
    Char_RawAt = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawLeftBracket");
    Char_RawLeftBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawBackslash");
    Char_RawBackslash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawRightBracket");
    Char_RawRightBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawWedge");
    Char_RawWedge = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawUnderscore");
    Char_RawUnderscore = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawBackquote");
    Char_RawBackquote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawLeftBrace");
    Char_RawLeftBrace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawVerticalBar");
    Char_RawVerticalBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawRightBrace");
    Char_RawRightBrace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RawTilde");
    Char_RawTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftGuillemet");
    Char_LeftGuillemet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DiscretionaryHyphen");
    Char_DiscretionaryHyphen = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightGuillemet");
    Char_RightGuillemet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalAGrave");
    Char_CapitalAGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalAAcute");
    Char_CapitalAAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalAHat");
    Char_CapitalAHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalATilde");
    Char_CapitalATilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalADoubleDot");
    Char_CapitalADoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalARing");
    Char_CapitalARing = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalAE");
    Char_CapitalAE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalCCedilla");
    Char_CapitalCCedilla = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEGrave");
    Char_CapitalEGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEAcute");
    Char_CapitalEAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEHat");
    Char_CapitalEHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEDoubleDot");
    Char_CapitalEDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalIGrave");
    Char_CapitalIGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalIAcute");
    Char_CapitalIAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalIHat");
    Char_CapitalIHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalIDoubleDot");
    Char_CapitalIDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEth");
    Char_CapitalEth = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalNTilde");
    Char_CapitalNTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOGrave");
    Char_CapitalOGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOAcute");
    Char_CapitalOAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOHat");
    Char_CapitalOHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOTilde");
    Char_CapitalOTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalODoubleDot");
    Char_CapitalODoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOSlash");
    Char_CapitalOSlash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUGrave");
    Char_CapitalUGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUAcute");
    Char_CapitalUAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUHat");
    Char_CapitalUHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUDoubleDot");
    Char_CapitalUDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalYAcute");
    Char_CapitalYAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalThorn");
    Char_CapitalThorn = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SZ");
    Char_SZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AGrave");
    Char_AGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AAcute");
    Char_AAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AHat");
    Char_AHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ATilde");
    Char_ATilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ADoubleDot");
    Char_ADoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ARing");
    Char_ARing = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AE");
    Char_AE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CCedilla");
    Char_CCedilla = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EGrave");
    Char_EGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EAcute");
    Char_EAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EHat");
    Char_EHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EDoubleDot");
    Char_EDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("IGrave");
    Char_IGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("IAcute");
    Char_IAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("IHat");
    Char_IHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("IDoubleDot");
    Char_IDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Eth");
    Char_Eth = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NTilde");
    Char_NTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OGrave");
    Char_OGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OAcute");
    Char_OAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OHat");
    Char_OHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OTilde");
    Char_OTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ODoubleDot");
    Char_ODoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OSlash");
    Char_OSlash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UGrave");
    Char_UGrave = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UAcute");
    Char_UAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UHat");
    Char_UHat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UDoubleDot");
    Char_UDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("YAcute");
    Char_YAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Thorn");
    Char_Thorn = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("YDoubleDot");
    Char_YDoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ABar");
    Char_ABar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalABar");
    Char_CapitalABar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ACup");
    Char_ACup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalACup");
    Char_CapitalACup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CAcute");
    Char_CAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalCAcute");
    Char_CapitalCAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CHacek");
    Char_CHacek = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalCHacek");
    Char_CapitalCHacek = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EBar");
    Char_EBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEBar");
    Char_CapitalEBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ECup");
    Char_ECup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalECup");
    Char_CapitalECup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ICup");
    Char_ICup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalICup");
    Char_CapitalICup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LSlash");
    Char_LSlash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalLSlash");
    Char_CapitalLSlash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ODoubleAcute");
    Char_ODoubleAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalODoubleAcute");
    Char_CapitalODoubleAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SHacek");
    Char_SHacek = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalSHacek");
    Char_CapitalSHacek = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UDoubleAcute");
    Char_UDoubleAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUDoubleAcute");
    Char_CapitalUDoubleAcute = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Florin");
    Char_Florin = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Breve");
    Char_Breve = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleDot");
    Char_DoubleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("TripleDot");
    Char_TripleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Hacek");
    Char_Hacek = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownBreve");
    Char_DownBreve = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Cedilla");
    Char_Cedilla = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalAlpha");
    Char_CapitalAlpha = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalBeta");
    Char_CapitalBeta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalGamma");
    Char_CapitalGamma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalDelta");
    Char_CapitalDelta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEpsilon");
    Char_CapitalEpsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalZeta");
    Char_CapitalZeta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalEta");
    Char_CapitalEta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalTheta");
    Char_CapitalTheta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalIota");
    Char_CapitalIota = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalKappa");
    Char_CapitalKappa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalLambda");
    Char_CapitalLambda = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalMu");
    Char_CapitalMu = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalNu");
    Char_CapitalNu = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalXi");
    Char_CapitalXi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOmicron");
    Char_CapitalOmicron = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalPi");
    Char_CapitalPi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalRho");
    Char_CapitalRho = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalSigma");
    Char_CapitalSigma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalTau");
    Char_CapitalTau = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalUpsilon");
    Char_CapitalUpsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyCapitalUpsilon");
    Char_CurlyCapitalUpsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalPhi");
    Char_CapitalPhi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalChi");
    Char_CapitalChi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalPsi");
    Char_CapitalPsi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalOmega");
    Char_CapitalOmega = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalDigamma");
    Char_CapitalDigamma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalStigma");
    Char_CapitalStigma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalKoppa");
    Char_CapitalKoppa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalSampi");
    Char_CapitalSampi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Alpha");
    Char_Alpha = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Beta");
    Char_Beta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Gamma");
    Char_Gamma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Delta");
    Char_Delta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Epsilon");
    Char_Epsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyEpsilon");
    Char_CurlyEpsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Zeta");
    Char_Zeta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Eta");
    Char_Eta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Theta");
    Char_Theta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyTheta");
    Char_CurlyTheta = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Iota");
    Char_Iota = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Kappa");
    Char_Kappa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyKappa");
    Char_CurlyKappa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Lambda");
    Char_Lambda = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mu");
    Char_Mu = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Nu");
    Char_Nu = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Xi");
    Char_Xi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Omicron");
    Char_Omicron = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Pi");
    Char_Pi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyPi");
    Char_CurlyPi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Rho");
    Char_Rho = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyRho");
    Char_CurlyRho = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sigma");
    Char_Sigma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FinalSigma");
    Char_FinalSigma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Tau");
    Char_Tau = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Upsilon");
    Char_Upsilon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Phi");
    Char_Phi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CurlyPhi");
    Char_CurlyPhi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Chi");
    Char_Chi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Psi");
    Char_Psi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Omega");
    Char_Omega = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Stigma");
    Char_Stigma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Digamma");
    Char_Digamma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Koppa");
    Char_Koppa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sampi");
    Char_Sampi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Infinity");
    Char_Infinity = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ExponentialE");
    Char_ExponentialE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ImaginaryI");
    Char_ImaginaryI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ImaginaryJ");
    Char_ImaginaryJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubledGamma");
    Char_DoubledGamma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubledPi");
    Char_DoubledPi = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ConstantC");
    Char_ConstantC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpPointer");
    Char_UpPointer = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightPointer");
    Char_RightPointer = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownPointer");
    Char_DownPointer = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftPointer");
    Char_LeftPointer = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptA");
    Char_ScriptA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptB");
    Char_ScriptB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptC");
    Char_ScriptC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptD");
    Char_ScriptD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptE");
    Char_ScriptE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptF");
    Char_ScriptF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptG");
    Char_ScriptG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptH");
    Char_ScriptH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptI");
    Char_ScriptI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptJ");
    Char_ScriptJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptK");
    Char_ScriptK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptL");
    Char_ScriptL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptM");
    Char_ScriptM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptN");
    Char_ScriptN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptO");
    Char_ScriptO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptP");
    Char_ScriptP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptQ");
    Char_ScriptQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptR");
    Char_ScriptR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptS");
    Char_ScriptS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptT");
    Char_ScriptT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptU");
    Char_ScriptU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptV");
    Char_ScriptV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptW");
    Char_ScriptW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptX");
    Char_ScriptX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptY");
    Char_ScriptY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptZ");
    Char_ScriptZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalA");
    Char_ScriptCapitalA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalB");
    Char_ScriptCapitalB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalC");
    Char_ScriptCapitalC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalD");
    Char_ScriptCapitalD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalE");
    Char_ScriptCapitalE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalF");
    Char_ScriptCapitalF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalG");
    Char_ScriptCapitalG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalH");
    Char_ScriptCapitalH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalI");
    Char_ScriptCapitalI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalJ");
    Char_ScriptCapitalJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalK");
    Char_ScriptCapitalK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalL");
    Char_ScriptCapitalL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalM");
    Char_ScriptCapitalM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalN");
    Char_ScriptCapitalN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalO");
    Char_ScriptCapitalO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalP");
    Char_ScriptCapitalP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalQ");
    Char_ScriptCapitalQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalR");
    Char_ScriptCapitalR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalS");
    Char_ScriptCapitalS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalT");
    Char_ScriptCapitalT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalU");
    Char_ScriptCapitalU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalV");
    Char_ScriptCapitalV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalW");
    Char_ScriptCapitalW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalX");
    Char_ScriptCapitalX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalY");
    Char_ScriptCapitalY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptCapitalZ");
    Char_ScriptCapitalZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicA");
    Char_GothicA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicB");
    Char_GothicB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicC");
    Char_GothicC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicD");
    Char_GothicD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicE");
    Char_GothicE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicF");
    Char_GothicF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicG");
    Char_GothicG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicH");
    Char_GothicH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicI");
    Char_GothicI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicJ");
    Char_GothicJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicK");
    Char_GothicK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicL");
    Char_GothicL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicM");
    Char_GothicM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicN");
    Char_GothicN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicO");
    Char_GothicO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicP");
    Char_GothicP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicQ");
    Char_GothicQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicR");
    Char_GothicR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicS");
    Char_GothicS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicT");
    Char_GothicT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicU");
    Char_GothicU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicV");
    Char_GothicV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicW");
    Char_GothicW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicX");
    Char_GothicX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicY");
    Char_GothicY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicZ");
    Char_GothicZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalA");
    Char_GothicCapitalA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalB");
    Char_GothicCapitalB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalC");
    Char_GothicCapitalC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalD");
    Char_GothicCapitalD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalE");
    Char_GothicCapitalE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalF");
    Char_GothicCapitalF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalG");
    Char_GothicCapitalG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalH");
    Char_GothicCapitalH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalI");
    Char_GothicCapitalI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalJ");
    Char_GothicCapitalJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalK");
    Char_GothicCapitalK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalL");
    Char_GothicCapitalL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalM");
    Char_GothicCapitalM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalN");
    Char_GothicCapitalN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalO");
    Char_GothicCapitalO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalP");
    Char_GothicCapitalP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalQ");
    Char_GothicCapitalQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalR");
    Char_GothicCapitalR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalS");
    Char_GothicCapitalS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalT");
    Char_GothicCapitalT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalU");
    Char_GothicCapitalU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalV");
    Char_GothicCapitalV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalW");
    Char_GothicCapitalW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalX");
    Char_GothicCapitalX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalY");
    Char_GothicCapitalY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicCapitalZ");
    Char_GothicCapitalZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckA");
    Char_DoubleStruckA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckB");
    Char_DoubleStruckB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckC");
    Char_DoubleStruckC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckD");
    Char_DoubleStruckD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckE");
    Char_DoubleStruckE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckF");
    Char_DoubleStruckF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckG");
    Char_DoubleStruckG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckH");
    Char_DoubleStruckH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckI");
    Char_DoubleStruckI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckJ");
    Char_DoubleStruckJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckK");
    Char_DoubleStruckK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckL");
    Char_DoubleStruckL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckM");
    Char_DoubleStruckM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckN");
    Char_DoubleStruckN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckO");
    Char_DoubleStruckO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckP");
    Char_DoubleStruckP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckQ");
    Char_DoubleStruckQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckR");
    Char_DoubleStruckR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckS");
    Char_DoubleStruckS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckT");
    Char_DoubleStruckT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckU");
    Char_DoubleStruckU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckV");
    Char_DoubleStruckV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckW");
    Char_DoubleStruckW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckX");
    Char_DoubleStruckX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckY");
    Char_DoubleStruckY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckZ");
    Char_DoubleStruckZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalA");
    Char_DoubleStruckCapitalA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalB");
    Char_DoubleStruckCapitalB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalC");
    Char_DoubleStruckCapitalC = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalD");
    Char_DoubleStruckCapitalD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalE");
    Char_DoubleStruckCapitalE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalF");
    Char_DoubleStruckCapitalF = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalG");
    Char_DoubleStruckCapitalG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalH");
    Char_DoubleStruckCapitalH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalI");
    Char_DoubleStruckCapitalI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalJ");
    Char_DoubleStruckCapitalJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalK");
    Char_DoubleStruckCapitalK = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalL");
    Char_DoubleStruckCapitalL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalM");
    Char_DoubleStruckCapitalM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalN");
    Char_DoubleStruckCapitalN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalO");
    Char_DoubleStruckCapitalO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalP");
    Char_DoubleStruckCapitalP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalQ");
    Char_DoubleStruckCapitalQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalR");
    Char_DoubleStruckCapitalR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalS");
    Char_DoubleStruckCapitalS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalT");
    Char_DoubleStruckCapitalT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalU");
    Char_DoubleStruckCapitalU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalV");
    Char_DoubleStruckCapitalV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalW");
    Char_DoubleStruckCapitalW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalX");
    Char_DoubleStruckCapitalX = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalY");
    Char_DoubleStruckCapitalY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckCapitalZ");
    Char_DoubleStruckCapitalZ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("WeierstrassP");
    Char_WeierstrassP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Aleph");
    Char_Aleph = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Bet");
    Char_Bet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Gimel");
    Char_Gimel = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Dalet");
    Char_Dalet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownExclamation");
    Char_DownExclamation = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Cent");
    Char_Cent = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sterling");
    Char_Sterling = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Currency");
    Char_Currency = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Euro");
    Char_Euro = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Yen");
    Char_Yen = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Section");
    Char_Section = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Copyright");
    Char_Copyright = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RegisteredTrademark");
    Char_RegisteredTrademark = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Trademark");
    Char_Trademark = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Degree");
    Char_Degree = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Micro");
    Char_Micro = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Paragraph");
    Char_Paragraph = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownQuestion");
    Char_DownQuestion = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HBar");
    Char_HBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mho");
    Char_Mho = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Angstrom");
    Char_Angstrom = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptySet");
    Char_EmptySet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Hyphen");
    Char_Hyphen = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Dash");
    Char_Dash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LongDash");
    Char_LongDash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Dagger");
    Char_Dagger = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleDagger");
    Char_DoubleDagger = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Bullet");
    Char_Bullet = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DotlessI");
    Char_DotlessI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DotlessJ");
    Char_DotlessJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FiLigature");
    Char_FiLigature = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FlLigature");
    Char_FlLigature = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptDotlessI");
    Char_ScriptDotlessI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptDotlessJ");
    Char_ScriptDotlessJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Angle");
    Char_Angle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightAngle");
    Char_RightAngle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("MeasuredAngle");
    Char_MeasuredAngle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SphericalAngle");
    Char_SphericalAngle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Diameter");
    Char_Diameter = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Ellipsis");
    Char_Ellipsis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VerticalEllipsis");
    Char_VerticalEllipsis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CenterEllipsis");
    Char_CenterEllipsis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AscendingEllipsis");
    Char_AscendingEllipsis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DescendingEllipsis");
    Char_DescendingEllipsis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Prime");
    Char_Prime = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoublePrime");
    Char_DoublePrime = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReversePrime");
    Char_ReversePrime = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReverseDoublePrime");
    Char_ReverseDoublePrime = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ForAll");
    Char_ForAll = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Exists");
    Char_Exists = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotExists");
    Char_NotExists = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Element");
    Char_Element = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotElement");
    Char_NotElement = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReverseElement");
    Char_ReverseElement = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotReverseElement");
    Char_NotReverseElement = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Because");
    Char_Because = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SuchThat");
    Char_SuchThat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VerticalSeparator");
    Char_VerticalSeparator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Therefore");
    Char_Therefore = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Implies");
    Char_Implies = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RoundImplies");
    Char_RoundImplies = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Tilde");
    Char_Tilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotTilde");
    Char_NotTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EqualTilde");
    Char_EqualTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("TildeEqual");
    Char_TildeEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotTildeEqual");
    Char_NotTildeEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("TildeFullEqual");
    Char_TildeFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("TildeTilde");
    Char_TildeTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotTildeTilde");
    Char_NotTildeTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotEqualTilde");
    Char_NotEqualTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotTildeFullEqual");
    Char_NotTildeFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessTilde");
    Char_LessTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterTilde");
    Char_GreaterTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessTilde");
    Char_NotLessTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterTilde");
    Char_NotGreaterTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTriangle");
    Char_LeftTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTriangle");
    Char_RightTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTriangleEqual");
    Char_LeftTriangleEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTriangleEqual");
    Char_RightTriangleEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTriangleBar");
    Char_LeftTriangleBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTriangleBar");
    Char_RightTriangleBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLeftTriangleBar");
    Char_NotLeftTriangleBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotRightTriangleBar");
    Char_NotRightTriangleBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLeftTriangle");
    Char_NotLeftTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLeftTriangleEqual");
    Char_NotLeftTriangleEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotRightTriangle");
    Char_NotRightTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotRightTriangleEqual");
    Char_NotRightTriangleEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotEqual");
    Char_NotEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLess");
    Char_NotLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreater");
    Char_NotGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessEqual");
    Char_LessEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessLess");
    Char_LessLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterGreater");
    Char_GreaterGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessEqual");
    Char_NotLessEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterEqual");
    Char_GreaterEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterEqual");
    Char_NotGreaterEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessSlantEqual");
    Char_LessSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessFullEqual");
    Char_LessFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessLess");
    Char_NotLessLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotNestedLessLess");
    Char_NotNestedLessLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessSlantEqual");
    Char_NotLessSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessFullEqual");
    Char_NotLessFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NestedLessLess");
    Char_NestedLessLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NestedGreaterGreater");
    Char_NestedGreaterGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterSlantEqual");
    Char_GreaterSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterFullEqual");
    Char_GreaterFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterGreater");
    Char_NotGreaterGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotNestedGreaterGreater");
    Char_NotNestedGreaterGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterSlantEqual");
    Char_NotGreaterSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterFullEqual");
    Char_NotGreaterFullEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessGreater");
    Char_LessGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterLess");
    Char_GreaterLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotLessGreater");
    Char_NotLessGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotGreaterLess");
    Char_NotGreaterLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LessEqualGreater");
    Char_LessEqualGreater = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GreaterEqualLess");
    Char_GreaterEqualLess = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Subset");
    Char_Subset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Superset");
    Char_Superset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSubset");
    Char_NotSubset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSuperset");
    Char_NotSuperset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SubsetEqual");
    Char_SubsetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SupersetEqual");
    Char_SupersetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSubsetEqual");
    Char_NotSubsetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSupersetEqual");
    Char_NotSupersetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareSubset");
    Char_SquareSubset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareSuperset");
    Char_SquareSuperset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareSubsetEqual");
    Char_SquareSubsetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareSupersetEqual");
    Char_SquareSupersetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSquareSubset");
    Char_NotSquareSubset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSquareSuperset");
    Char_NotSquareSuperset = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSquareSubsetEqual");
    Char_NotSquareSubsetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSquareSupersetEqual");
    Char_NotSquareSupersetEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Precedes");
    Char_Precedes = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Succeeds");
    Char_Succeeds = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("PrecedesEqual");
    Char_PrecedesEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SucceedsEqual");
    Char_SucceedsEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("PrecedesTilde");
    Char_PrecedesTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SucceedsTilde");
    Char_SucceedsTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotPrecedes");
    Char_NotPrecedes = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSucceeds");
    Char_NotSucceeds = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("PrecedesSlantEqual");
    Char_PrecedesSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotPrecedesEqual");
    Char_NotPrecedesEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotPrecedesSlantEqual");
    Char_NotPrecedesSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotPrecedesTilde");
    Char_NotPrecedesTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SucceedsSlantEqual");
    Char_SucceedsSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSucceedsEqual");
    Char_NotSucceedsEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSucceedsSlantEqual");
    Char_NotSucceedsSlantEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotSucceedsTilde");
    Char_NotSucceedsTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpTee");
    Char_UpTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Proportional");
    Char_Proportional = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Proportion");
    Char_Proportion = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Congruent");
    Char_Congruent = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotCongruent");
    Char_NotCongruent = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CupCap");
    Char_CupCap = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotCupCap");
    Char_NotCupCap = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Equilibrium");
    Char_Equilibrium = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReverseEquilibrium");
    Char_ReverseEquilibrium = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpEquilibrium");
    Char_UpEquilibrium = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReverseUpEquilibrium");
    Char_ReverseUpEquilibrium = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTee");
    Char_RightTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTee");
    Char_LeftTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownTee");
    Char_DownTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleRightTee");
    Char_DoubleRightTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLeftTee");
    Char_DoubleLeftTee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HumpEqual");
    Char_HumpEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotHumpEqual");
    Char_NotHumpEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HumpDownHump");
    Char_HumpDownHump = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotHumpDownHump");
    Char_NotHumpDownHump = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DotEqual");
    Char_DotEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Colon");
    Char_Colon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Equal");
    Char_Equal = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LongEqual");
    Char_LongEqual = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sqrt");
    Char_Sqrt = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VerticalBar");
    Char_VerticalBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotVerticalBar");
    Char_NotVerticalBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleVerticalBar");
    Char_DoubleVerticalBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NotDoubleVerticalBar");
    Char_NotDoubleVerticalBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Not");
    Char_Not = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VerticalTilde");
    Char_VerticalTilde = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Times");
    Char_Times = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisibleTimes");
    Char_InvisibleTimes = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("PlusMinus");
    Char_PlusMinus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("MinusPlus");
    Char_MinusPlus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Divide");
    Char_Divide = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CenterDot");
    Char_CenterDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SmallCircle");
    Char_SmallCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Cross");
    Char_Cross = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CirclePlus");
    Char_CirclePlus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CircleMinus");
    Char_CircleMinus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CircleTimes");
    Char_CircleTimes = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CircleDot");
    Char_CircleDot = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Star");
    Char_Star = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Square");
    Char_Square = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Diamond");
    Char_Diamond = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Del");
    Char_Del = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Backslash");
    Char_Backslash = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Cap");
    Char_Cap = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Cup");
    Char_Cup = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Coproduct");
    Char_Coproduct = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Integral");
    Char_Integral = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ContourIntegral");
    Char_ContourIntegral = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleContourIntegral");
    Char_DoubleContourIntegral = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CounterClockwiseContourIntegral");
    Char_CounterClockwiseContourIntegral = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ClockwiseContourIntegral");
    Char_ClockwiseContourIntegral = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sum");
    Char_Sum = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Product");
    Char_Product = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Intersection");
    Char_Intersection = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Union");
    Char_Union = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UnionPlus");
    Char_UnionPlus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareIntersection");
    Char_SquareIntersection = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SquareUnion");
    Char_SquareUnion = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Wedge");
    Char_Wedge = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("And");
    Char_And = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Nand");
    Char_Nand = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Vee");
    Char_Vee = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Or");
    Char_Or = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Nor");
    Char_Nor = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Xor");
    Char_Xor = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("PartialD");
    Char_PartialD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DifferentialD");
    Char_DifferentialD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CapitalDifferentialD");
    Char_CapitalDifferentialD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightArrow");
    Char_RightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftArrow");
    Char_LeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpArrow");
    Char_UpArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownArrow");
    Char_DownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftRightArrow");
    Char_LeftRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpDownArrow");
    Char_UpDownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ShortRightArrow");
    Char_ShortRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ShortLeftArrow");
    Char_ShortLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ShortUpArrow");
    Char_ShortUpArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ShortDownArrow");
    Char_ShortDownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RuleDelayed");
    Char_RuleDelayed = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Rule");
    Char_Rule = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleRightArrow");
    Char_DoubleRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLeftArrow");
    Char_DoubleLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleUpArrow");
    Char_DoubleUpArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleDownArrow");
    Char_DoubleDownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLeftRightArrow");
    Char_DoubleLeftRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleUpDownArrow");
    Char_DoubleUpDownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightArrowBar");
    Char_RightArrowBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftArrowBar");
    Char_LeftArrowBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpArrowBar");
    Char_UpArrowBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownArrowBar");
    Char_DownArrowBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTeeArrow");
    Char_RightTeeArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTeeArrow");
    Char_LeftTeeArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpTeeArrow");
    Char_UpTeeArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownTeeArrow");
    Char_DownTeeArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpperLeftArrow");
    Char_UpperLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpperRightArrow");
    Char_UpperRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LowerRightArrow");
    Char_LowerRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LowerLeftArrow");
    Char_LowerLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LongRightArrow");
    Char_LongRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LongLeftArrow");
    Char_LongLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLongLeftArrow");
    Char_DoubleLongLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLongRightArrow");
    Char_DoubleLongRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LongLeftRightArrow");
    Char_LongLeftRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleLongLeftRightArrow");
    Char_DoubleLongLeftRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightArrowLeftArrow");
    Char_RightArrowLeftArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftArrowRightArrow");
    Char_LeftArrowRightArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UpArrowDownArrow");
    Char_UpArrowDownArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownArrowUpArrow");
    Char_DownArrowUpArrow = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightVector");
    Char_RightVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownRightVector");
    Char_DownRightVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftVector");
    Char_LeftVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownLeftVector");
    Char_DownLeftVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightUpVector");
    Char_RightUpVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftUpVector");
    Char_LeftUpVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightDownVector");
    Char_RightDownVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftDownVector");
    Char_LeftDownVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftRightVector");
    Char_LeftRightVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownLeftRightVector");
    Char_DownLeftRightVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightUpDownVector");
    Char_RightUpDownVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftUpDownVector");
    Char_LeftUpDownVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightVectorBar");
    Char_RightVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownRightVectorBar");
    Char_DownRightVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftVectorBar");
    Char_LeftVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownLeftVectorBar");
    Char_DownLeftVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightUpVectorBar");
    Char_RightUpVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftUpVectorBar");
    Char_LeftUpVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightDownVectorBar");
    Char_RightDownVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftDownVectorBar");
    Char_LeftDownVectorBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightTeeVector");
    Char_RightTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownRightTeeVector");
    Char_DownRightTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftTeeVector");
    Char_LeftTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DownLeftTeeVector");
    Char_DownLeftTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightUpTeeVector");
    Char_RightUpTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftUpTeeVector");
    Char_LeftUpTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightDownTeeVector");
    Char_RightDownTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftDownTeeVector");
    Char_LeftDownTeeVector = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftDoubleBracket");
    Char_LeftDoubleBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightDoubleBracket");
    Char_RightDoubleBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftAngleBracket");
    Char_LeftAngleBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightAngleBracket");
    Char_RightAngleBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftFloor");
    Char_LeftFloor = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightFloor");
    Char_RightFloor = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftCeiling");
    Char_LeftCeiling = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightCeiling");
    Char_RightCeiling = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftBracketingBar");
    Char_LeftBracketingBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightBracketingBar");
    Char_RightBracketingBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftDoubleBracketingBar");
    Char_LeftDoubleBracketingBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightDoubleBracketingBar");
    Char_RightDoubleBracketingBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DottedSquare");
    Char_DottedSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptySmallCircle");
    Char_EmptySmallCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledSmallCircle");
    Char_FilledSmallCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyCircle");
    Char_EmptyCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledCircle");
    Char_FilledCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyDiamond");
    Char_EmptyDiamond = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledDiamond");
    Char_FilledDiamond = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyRectangle");
    Char_EmptyRectangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledRectangle");
    Char_FilledRectangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptySquare");
    Char_EmptySquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptySmallSquare");
    Char_EmptySmallSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyVerySmallSquare");
    Char_EmptyVerySmallSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledSquare");
    Char_FilledSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledSmallSquare");
    Char_FilledSmallSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledVerySmallSquare");
    Char_FilledVerySmallSquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyUpTriangle");
    Char_EmptyUpTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledUpTriangle");
    Char_FilledUpTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledRightTriangle");
    Char_FilledRightTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EmptyDownTriangle");
    Char_EmptyDownTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledDownTriangle");
    Char_FilledDownTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FilledLeftTriangle");
    Char_FilledLeftTriangle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FivePointedStar");
    Char_FivePointedStar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SixPointedStar");
    Char_SixPointedStar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GraySquare");
    Char_GraySquare = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GrayCircle");
    Char_GrayCircle = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LetterSpace");
    Char_LetterSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("WatchIcon");
    Char_WatchIcon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KernelIcon");
    Char_KernelIcon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("MathematicaIcon");
    Char_MathematicaIcon = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Flat");
    Char_Flat = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Natural");
    Char_Natural = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Sharp");
    Char_Sharp = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpadeSuit");
    Char_SpadeSuit = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HeartSuit");
    Char_HeartSuit = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DiamondSuit");
    Char_DiamondSuit = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ClubSuit");
    Char_ClubSuit = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Wolf");
    Char_Wolf = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Villa");
    Char_Villa = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Akuz");
    Char_Akuz = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Andy");
    Char_Andy = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Spooky");
    Char_Spooky = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HappySmiley");
    Char_HappySmiley = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SadSmiley");
    Char_SadSmiley = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FreakedSmiley");
    Char_FreakedSmiley = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NeutralSmiley");
    Char_NeutralSmiley = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LightBulb");
    Char_LightBulb = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NumberSign");
    Char_NumberSign = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("WarningSign");
    Char_WarningSign = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonA");
    Char_KlingonA = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonB");
    Char_KlingonB = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonCH");
    Char_KlingonCH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonD");
    Char_KlingonD = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonE");
    Char_KlingonE = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonGH");
    Char_KlingonGH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonH");
    Char_KlingonH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonI");
    Char_KlingonI = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonJ");
    Char_KlingonJ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonL");
    Char_KlingonL = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonM");
    Char_KlingonM = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonN");
    Char_KlingonN = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonNG");
    Char_KlingonNG = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonO");
    Char_KlingonO = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonP");
    Char_KlingonP = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonQ");
    Char_KlingonQ = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonQH");
    Char_KlingonQH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonR");
    Char_KlingonR = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonS");
    Char_KlingonS = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonT");
    Char_KlingonT = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonTLH");
    Char_KlingonTLH = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonU");
    Char_KlingonU = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonV");
    Char_KlingonV = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonW");
    Char_KlingonW = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonY");
    Char_KlingonY = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonGlottalStop");
    Char_KlingonGlottalStop = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon0");
    Char_Klingon0 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon1");
    Char_Klingon1 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon2");
    Char_Klingon2 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon3");
    Char_Klingon3 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon4");
    Char_Klingon4 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon5");
    Char_Klingon5 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon6");
    Char_Klingon6 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon7");
    Char_Klingon7 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon8");
    Char_Klingon8 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Klingon9");
    Char_Klingon9 = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KlingonEmpire");
    Char_KlingonEmpire = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UnknownGlyph");
    Char_UnknownGlyph = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ImplicitPlus");
    Char_ImplicitPlus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisibleSpace");
    Char_InvisibleSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VeryThinSpace");
    Char_VeryThinSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ThinSpace");
    Char_ThinSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("MediumSpace");
    Char_MediumSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ThickSpace");
    Char_ThickSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NegativeVeryThinSpace");
    Char_NegativeVeryThinSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NegativeThinSpace");
    Char_NegativeThinSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NegativeMediumSpace");
    Char_NegativeMediumSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NegativeThickSpace");
    Char_NegativeThickSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OpenCurlyQuote");
    Char_OpenCurlyQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CloseCurlyQuote");
    Char_CloseCurlyQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OpenCurlyDoubleQuote");
    Char_OpenCurlyDoubleQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CloseCurlyDoubleQuote");
    Char_CloseCurlyDoubleQuote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OverParenthesis");
    Char_OverParenthesis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UnderParenthesis");
    Char_UnderParenthesis = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OverBrace");
    Char_OverBrace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UnderBrace");
    Char_UnderBrace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OverBracket");
    Char_OverBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("UnderBracket");
    Char_UnderBracket = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Null");
    Char_Null = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NewLine");
    Char_NewLine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("IndentingNewLine");
    Char_IndentingNewLine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NoBreak");
    Char_NoBreak = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("COMPATIBILITYNoBreak");
    Char_COMPATIBILITYNoBreak = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NonBreakingSpace");
    Char_NonBreakingSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Continuation");
    Char_Continuation = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpaceIndicator");
    Char_SpaceIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RoundSpaceIndicator");
    Char_RoundSpaceIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisiblePrefixScriptBase");
    Char_InvisiblePrefixScriptBase = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisiblePostfixScriptBase");
    Char_InvisiblePostfixScriptBase = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpanFromLeft");
    Char_SpanFromLeft = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpanFromAbove");
    Char_SpanFromAbove = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpanFromBoth");
    Char_SpanFromBoth = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CommandKey");
    Char_CommandKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftModified");
    Char_LeftModified = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightModified");
    Char_RightModified = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisibleApplication");
    Char_InvisibleApplication = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CloverLeaf");
    Char_CloverLeaf = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ControlKey");
    Char_ControlKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EscapeKey");
    Char_EscapeKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("TabKey");
    Char_TabKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SpaceKey");
    Char_SpaceKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DeleteKey");
    Char_DeleteKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AltKey");
    Char_AltKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("OptionKey");
    Char_OptionKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("KeyBar");
    Char_KeyBar = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EnterKey");
    Char_EnterKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SystemEnterKey");
    Char_SystemEnterKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ShiftKey");
    Char_ShiftKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mod1Key");
    Char_Mod1Key = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mod2Key");
    Char_Mod2Key = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AliasDelimiter");
    Char_AliasDelimiter = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AliasIndicator");
    Char_AliasIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReturnIndicator");
    Char_ReturnIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LineSeparator");
    Char_LineSeparator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ParagraphSeparator");
    Char_ParagraphSeparator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DiscretionaryLineSeparator");
    Char_DiscretionaryLineSeparator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DiscretionaryParagraphSeparator");
    Char_DiscretionaryParagraphSeparator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HorizontalLine");
    Char_HorizontalLine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("VerticalLine");
    Char_VerticalLine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("InvisibleComma");
    Char_InvisibleComma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("NumberComma");
    Char_NumberComma = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ReturnKey");
    Char_ReturnKey = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SelectionPlaceholder");
    Char_SelectionPlaceholder = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Placeholder");
    Char_Placeholder = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AlignmentMarker");
    Char_AlignmentMarker = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("SkeletonIndicator");
    Char_SkeletonIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LeftSkeleton");
    Char_LeftSkeleton = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("RightSkeleton");
    Char_RightSkeleton = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ErrorIndicator");
    Char_ErrorIndicator = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AutoSpace");
    Char_AutoSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AutoOperand");
    Char_AutoOperand = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AutoPlaceholder");
    Char_AutoPlaceholder = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AutoLeftMatch");
    Char_AutoLeftMatch = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("AutoRightMatch");
    Char_AutoRightMatch = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckZero");
    Char_DoubleStruckZero = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckOne");
    Char_DoubleStruckOne = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckTwo");
    Char_DoubleStruckTwo = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckThree");
    Char_DoubleStruckThree = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckFour");
    Char_DoubleStruckFour = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckFive");
    Char_DoubleStruckFive = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckSix");
    Char_DoubleStruckSix = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckSeven");
    Char_DoubleStruckSeven = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckEight");
    Char_DoubleStruckEight = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("DoubleStruckNine");
    Char_DoubleStruckNine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicZero");
    Char_GothicZero = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicOne");
    Char_GothicOne = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicTwo");
    Char_GothicTwo = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicThree");
    Char_GothicThree = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicFour");
    Char_GothicFour = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicFive");
    Char_GothicFive = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicSix");
    Char_GothicSix = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicSeven");
    Char_GothicSeven = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicEight");
    Char_GothicEight = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("GothicNine");
    Char_GothicNine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptZero");
    Char_ScriptZero = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptOne");
    Char_ScriptOne = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptTwo");
    Char_ScriptTwo = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptThree");
    Char_ScriptThree = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptFour");
    Char_ScriptFour = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptFive");
    Char_ScriptFive = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptSix");
    Char_ScriptSix = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptSeven");
    Char_ScriptSeven = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptEight");
    Char_ScriptEight = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ScriptNine");
    Char_ScriptNine = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mercury");
    Char_Mercury = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Venus");
    Char_Venus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Earth");
    Char_Earth = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Mars");
    Char_Mars = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Jupiter");
    Char_Jupiter = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Saturn");
    Char_Saturn = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Uranus");
    Char_Uranus = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Neptune");
    Char_Neptune = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Pluto");
    Char_Pluto = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("FirstPage");
    Char_FirstPage = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("LastPage");
    Char_LastPage = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("QuarterNote");
    Char_QuarterNote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EighthNote");
    Char_EighthNote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("BeamedEighthNote");
    Char_BeamedEighthNote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("BeamedSixteenthNote");
    Char_BeamedSixteenthNote = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EntityStart");
    Char_EntityStart = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("EntityEnd");
    Char_EntityEnd = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Checkmark");
    Char_Checkmark = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CheckmarkedBox");
    Char_CheckmarkedBox = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("CheckedBox");
    Char_CheckedBox = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Piecewise");
    Char_Piecewise = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Transpose");
    Char_Transpose = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Conjugate");
    Char_Conjugate = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("HermitianConjugate");
    Char_HermitianConjugate = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("ConjugateTranspose");
    Char_ConjugateTranspose = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("StepperRight");
    Char_StepperRight = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("StepperLeft");
    Char_StepperLeft = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("StepperUp");
    Char_StepperUp = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("StepperDown");
    Char_StepperDown = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("Divides");
    Char_Divides = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
{
    MString s = MString_NewC("COMPATIBILITYKanjiSpace");
    Char_COMPATIBILITYKanjiSpace = GetUnicodeCharacterCode(s);
    MString_Release(s);
}
